version: '3.8'

services:
  rating_service:
    build: ./rating_service
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

  notification_service:
    build: ./notification_service
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rating
      POSTGRES_PASSWORD: rating
      POSTGRES_DB: ratingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rating -d ratingdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
