# Use Go Image
FROM golang:1.23-alpine

# Create and set app directory
WORKDIR /app

# Copy dependency files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy other files
COPY . .

# Get build of service
RUN go build -o rating_service ./cmd

# Run the service
CMD ["./rating_service"]
